spring.application.name=SWP391_QuitSmoking_BE
spring.main.allow-circular-references=true

spring.datasource.url=jdbc:postgresql://localhost:5432/QuitSmokingDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.allow-cicular-references=true

application.security.jwt.secret-key=4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=604800000
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.root=ERROR
#logging.level.org.springframework.mail=DEBUG
#logging.level.org.springframework=DEBUG

logging.level.com.swp391project.SWP391_QuitSmoking_BE=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.engine.transaction=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.java.sql=DEBUG
logging.level.org.hibernate.engine.jdbc=TRACE



spring.mail.host=smtp.gmail.com
spring.mail.port=587



spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
logging.level.org.springframework.mail.javamail=TRACE

#spring.mail.properties.mail.smtp.socketFactory.port=465
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.fallback=false
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.mail.default-encoding=UTF-8

agora.app-id=73772d47dadb46d188682cf077fe4e64
agora.app-certificate=ba6549fe54794841bcf112bf3615f22b

vnpay.tmnCode=ZA6FG78P
vnpay.hashSecret=Z25RB7TCSI1YRL6BXEZSORFP042ZQ8V8
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnpay.returnUrl=http://localhost:8080/api/vnpay/payment-return
vnpay.ipnUrl=http://localhost:8080/api/vnpay/ipn