package com.swp391project.SWP391_QuitSmoking_BE.enums;

public enum Situation {
    AFTER_SEX,
    AT_BAR,
    AT_PARTY,
    AT_EVENT,
    WORKING,
    BBQ,
    DRIVING,
    WATCHING_TV,
    ON_PHONE,
    ON_COMPUTER,
    CANT_SLEEP,
    CHATITNG,
    CLEANING,
    COOKING,
    DRINKING,
    SITTING_ON_CAR,
    GAMING,
    THINKING,
    GOING_TO_BED,
    HAIVNG_A_BREAK,
    JUST_EATEN,
    READING,
    SHOPPING,
    RELAXING,
    WALKING,
    WAITING,
    SOCIALIZING,
    WAKING_UP,
    WORK_BREAK,
    OTHER // Dùng để lưu các tình huống khác không có trong danh sách
}
